modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/marcus8448/Pack-Utils/issues"
[[mods]]
modId="modpackutils"
version="1.14.4-1.0.0.0"
displayName="Modpack Utils"
displayURL="https://www.curseforge.com/minecraft/mc-mods/modpack-utils"
authors="marcus8448"
description='''
Misc utils for pack authors
'''
[[dependencies.modpackutils]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modpackutils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
